version: "3"

services:

  express:
    build:
      context: ./
      dockerfile: Dockerfile
    working_dir: /src
    volumes:
      - ./src:/src
    depends_on:
      - mongo
    environment:
      NODE_ENV: development
    ports:
      - "3000:3000"
    command: nodemon -L server/server.js

  mongo:
    container_name: mongo
    image: mongo:latest
    ports: 
      - "27017:27017"
    volumes:
      - ./src/data/db:/data/db
